apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hrd5dobug-java-quarkus
  janus-idp.io/tekton: hrd5dobug-java-quarkus
  backstage.io/kubernetes-id: hrd5dobug-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: hrd5dobug-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
